"""build-distribution.py -- assemble the shippable pipeline. Allowlist only.

    python lib/build-distribution.py [--out DIR] [--with-testcases] [--check]

      --out             where to build (default: ../straylight-pipeline)
      --with-testcases  include the regression suite's source
      --check           verify an existing build; write nothing, exit non-zero
                        if anything is wrong

WHY AN ALLOWLIST AND NEVER A DIRECTORY COPY
-------------------------------------------
`lib/` and `survey/` hold 530 MB, of which 266 KB is source. The other 99.95%
is run output -- 88 .lpf ray files at 450 MB, 643 .xmp result maps, 643 Speos
HTML reports, 83 SpaceClaim documents. A recursive copy ships all of it.

Size is the least of it. Three things in that tree must never leave:

  * `lib/fleet-codever.log` and `survey/wide100-couplegate.log` contain licence
    error text quoting the Ansys ACCOUNT NUMBER.
  * The 22 `.zmx` prescriptions are Zemax's sample lenses. The corpus export
    already established they are not ours to redistribute; a directory copy
    would quietly reverse that decision.
  * `straylight.toml` describes ONE machine. Shipping it means a customer
    inherits paths that do not exist, and the config check they were told to
    run passes on a file they never wrote. Only the `.example` ships.

So the rule is inverted from the usual: nothing is included unless a rule below
names it, and everything excluded is COUNTED and reported. A build that
silently dropped a needed file would look exactly like a clean build.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sanitise import IDENT, read, sanitise, text, write  # noqa: E402

# (source dir relative to BASE, allowed extensions). Directories are NOT
# walked recursively: every subdirectory under these is run output.
CODE = [
    ("lib", (".py", ".ps1")),
    ("survey", (".py", ".ps1")),
]
TESTS = [("testcases", (".py", ".ps1", ".sh"))]

# The regression suite's SCRIPTS are useless without the case definitions they
# score against. Shipping the scripts alone produced a build that printed
# BUILD OK and then, on first run, either crashed on a missing specs.json or --
# worse, with specs.json but no case metadata -- exited 0 and reported
# "0 correct". A silent zero is this codebase's signature failure, so the data
# below is not optional to `--with-testcases`; it IS `--with-testcases`.
#
# Determined by measurement, not by reading the code: staged one file class at
# a time until `score-preflight.py` in the build reproduced the live tree
# exactly (22 correct; A-ghost 38/38, B-stray 32/32, C-edge 31/31).
# (subdir, exact names or None, allowed extensions or None)
TEST_DATA = [
    ("testcases", ("specs.json",), None),        # the 100 case definitions
    # Every gate verdict -- but by EXTENSION, never "everything in the folder".
    # The first version took the whole directory and swept in 101 zero-byte
    # `.preflight.txt.err` files; the banned-extension check caught it, which
    # is the second time in this file that one rule has caught another's
    # sloppiness. Name what you want.
    ("testcases/preflight", None, (".json", ".txt")),
]
# Per-case, under testcases/cases/<id>/. NOT the .zmx beside them: those are
# Zemax's sample prescriptions, and the corpus export already established they
# are not ours to redistribute.
TEST_CASE_FILES = (".built.json", ".job.json")

# Root-level files the pipeline actually needs. The BSDF is ours (generated by
# make-bsdf.py) and is referenced by run-backtrace.py and run-queue.ps1 as
# $BASE\black-anodize-plausible.anisotropicbsdf, so the pipeline does not run
# without it.
ROOT_FILES = [
    # THE ENTRY POINT. Absent until 2026-08-13, and nothing noticed because
    # every check in this file inspects what the pipeline needs to RUN, and a
    # customer who cannot tell what to run first never reaches a runtime check.
    # The build verified clean, the fleet ran green from it, and the unpacked
    # tree was still eight directories with no starting instruction. Both of
    # these ship: the README says what this is, the PDF says how to install it.
    # Every end-to-end rehearsal until now read the guide from the DEV tree,
    # which is exactly how the omission survived a "follow the guide as a
    # customer would" test.
    "README.md",
    "toolchain-install-a4.pdf",
    "LICENSE",
    "NOTICE.md",
    "straylight.toml.example",
    "requirements.txt",
    "black-anodize-plausible.anisotropicbsdf",
    # The ODX export stage shells out to this. Omitted until 2026-08-09, when a
    # full fleet run from a built distribution died at `odx` after 30 seconds:
    # runner.st_odx does os.path.join(BASE, "export-odx.ps1") and the file was
    # not there. Nothing caught it -- the import graph cannot see a script
    # invoked by PATH rather than imported. See ROOT_REF below.
    "export-odx.ps1",
    # Same story one stage later: runner.st_s0 runs ghost/s0-ghosts.ps1. The
    # rest of ghost/ is Double Gauss ghost-optimisation research with hardcoded
    # DG paths and does NOT ship -- only this one file is pipeline.
    "ghost/s0-ghosts.ps1",
    # And a third: runner._sim looks for its wire script in survey/ and FALLS
    # BACK to testcases/, so the optics-only stage needs this one file even
    # when the regression suite is not shipped. Found the same way -- the
    # fleet run reached sim_optics and stopped.
    "testcases/wire-optics-only.py",
    # THE WALL-BSDF BAND, added 2026-08-13. The README tells a reader to bound
    # the wall-model uncertainty themselves, and that instruction is worthless
    # without the driver and the two bracketing models.
    #
    # `make-bsdf-band.py`, which BUILT these two, deliberately does NOT ship: it
    # imports `ansys_optical_automation`, which is Ansys's own MIT library,
    # excluded from this build on necessity grounds and fetched separately per
    # the install guide. Shipping the generator would either fail the
    # undeclared-third-party-import check or need an exemption for a package
    # that is not part of the Ansys install -- so the MODELS ship pre-built and
    # the README states how they were derived. There is no redistribution
    # question about the .anisotropicbsdf files themselves: they are ours,
    # generated from our own scatter model.
    "run-bsdf-band.py",
    "black-anodize-low.anisotropicbsdf",
    "black-anodize-high.anisotropicbsdf",
]

# Files referenced as `os.path.join(BASE, "x")` or `$BASE\x` by shipped code.
# `[A-Za-z0-9]+` for the extension, NOT `[a-z]+`: the scan that first built
# ROOT_FILES used the latter and so could never match `ps1`, silently hiding
# every PowerShell script at the root. That single character is why the
# distribution shipped broken.
# MULTI-SEGMENT on purpose: the single-segment version caught export-odx.ps1
# and then missed os.path.join(BASE, "ghost", "s0-ghosts.ps1") one stage later,
# so the same failure was discovered twice by 6-minute fleet runs instead of
# once by a check.
ROOT_REF = re.compile(
    r'os\.path\.join\(\s*BASE\s*,\s*((?:"[^"]+"\s*,\s*)*"[^"]+")\s*\)'
    r'|\$BASE\\([A-Za-z0-9._\\-]+\.[A-Za-z0-9]+)')

# Modules that are neither stdlib nor ours. Anything a shipped file imports
# from outside this set must appear in requirements.txt, or the customer gets
# an ImportError on first use from a build that verified clean -- the local
# import check below cannot see it, because it only resolves OUR modules.
STDLIB = set("""
argparse ast atexit base64 collections contextlib copy csv datetime difflib
enum functools glob hashlib io itertools json logging math os pathlib pickle
platform pprint random re shutil signal socket string subprocess sys tempfile
textwrap threading time traceback types typing unittest urllib uuid warnings
xml zipfile abc binascii calendar cmath codecs ctypes decimal errno fnmatch
fractions gc getpass gzip heapq inspect locale operator posixpath queue
selectors shlex stat statistics struct tarfile timeit token tokenize unicodedata
weakref webbrowser
""".split())

# Third-party, but NOT installable and so never in requirements.txt. Two
# sources, both satisfied by `ansys_root` in straylight.toml (which settings.py
# validates), neither by pip:
#   * the Illumine SWIG bindings, reached by appending settings.SPEOS_BIN to
#     sys.path at run time;
#   * `clr` and `System`, which exist only inside Speos' IronPython host and
#     are how a wire script reaches .NET at all.
# Exempted EXPLICITLY rather than silently, because "not on PyPI" and "we
# forgot to declare it" look identical in a requirements file. Both entries
# were added because the check flagged them -- it is working, not noisy.
ANSYS_PROVIDED = {"IllumineCore_pywrap", "IllumineSpeos_pywrap",
                  "clr", "System"}

# Third-party and installable, but used only by THIS file, which is build
# tooling the customer never runs. Putting pypdf in requirements.txt would make
# every customer install a PDF library to run an optical simulation. Exempted
# by name rather than by "it's only in build-distribution.py", so adding a
# second build-time dependency is a deliberate edit here and not a silent one.
BUILD_ONLY = {"pypdf"}

# The entry-point documents, and what makes them non-empty. A README that
# shipped as a stub would satisfy every presence check in this file, so the
# check below requires the two things a first-time reader must find: the
# config file they have to create, and a command they can actually run.
DOC_README = "README.md"
DOC_GUIDE = "toolchain-install-a4.pdf"
DOC_MUST_MENTION = ("straylight.toml", "settings.py", "run-fleet.py",
                    "first-run.py", "make-samples.py")

# Never, under any rule. Checked again after the build as a backstop, because
# the allowlist and this list are meant to disagree about nothing.
BANNED_EXT = (".lpf", ".xmp", ".html", ".scdocx", ".step", ".zmx", ".zda",
              ".log", ".odx", ".out", ".err", ".pid")
BANNED_NAME = ("straylight.toml",)
BINARY_EXT = (".anisotropicbsdf", ".bsdf", ".bsdf180", ".pdf", ".png")
ACCOUNT = re.compile(r"\baccount\s+\d{6,}", re.I)

# ATTRIBUTION, WHICH IS NOT WHAT `IDENT` CHECKS. Discovered 2026-08-13: IDENT
# is `C:[\\/]Users[\\/]bob` -- a HOME-DIRECTORY PATH. It has always been a path
# check, while this file printed "operator name .......... absent" next to it.
# That label claimed a guarantee nobody had implemented: nothing verified that
# the shipped material is unattributed, which is a standing requirement for the
# reference documents.
#
# The two are genuinely different rules and both are wanted:
#   * a leaked home path is a mistake anywhere, including in LICENSE;
#   * a NAME is required in LICENSE and NOTICE.md, where the MIT copyright line
#     lives, and must appear nowhere else -- the README, the install guide and
#     the code are meant to stand on their own.
# So this is scoped, not global. A blanket ban would fail the copyright notice,
# which is the one place the name is correct.
# SPLIT ACROSS TWO LITERALS ON PURPOSE. This file ships, and the scanner runs
# over every shipped file including itself -- written as one literal, the
# pattern matches its own source and every build fails on build-distribution.py.
# Adjacent byte literals join at compile time, so the regex is exactly the same
# while the contiguous string never appears on disk. (`Five\s*Talent` needs no
# such treatment: the `\s*` between the words is backslash-s-asterisk in the
# source, which is not whitespace, so the pattern cannot match its own text.)
ATTRIB = re.compile(rb"(?i)House" rb"holder|Five\s*Talent")
ATTRIB_ALLOWED = {"LICENSE", "NOTICE.md"}


def sources(with_tests):
    """(relative path, absolute source path) for every file that ships."""
    for name in ROOT_FILES:
        p = os.path.join(BASE, name)
        if os.path.isfile(p):
            yield name, p
    for sub, exts in CODE + (TESTS if with_tests else []):
        d = os.path.join(BASE, sub)
        for f in sorted(os.listdir(d)):
            if f.endswith(exts) and os.path.isfile(os.path.join(d, f)):
                yield "%s/%s" % (sub, f), os.path.join(d, f)
    if not with_tests:
        return
    for sub, names, exts in TEST_DATA:
        d = os.path.join(BASE, sub.replace("/", os.sep))
        if not os.path.isdir(d):
            continue
        for f in sorted(os.listdir(d)):
            p = os.path.join(d, f)
            if not os.path.isfile(p):
                continue
            if names is not None and f not in names:
                continue
            if exts is not None and not f.lower().endswith(exts):
                continue
            yield "%s/%s" % (sub, f), p
    cases = os.path.join(BASE, "testcases", "cases")
    if os.path.isdir(cases):
        for cid in sorted(os.listdir(cases)):
            cd = os.path.join(cases, cid)
            if not os.path.isdir(cd):
                continue
            for f in sorted(os.listdir(cd)):
                if f.endswith(TEST_CASE_FILES):
                    yield "testcases/cases/%s/%s" % (cid, f), os.path.join(cd, f)


def excluded(with_tests):
    """What was left behind, by class -- so the report can say so out loud."""
    out = {}
    for sub, exts in CODE + (TESTS if with_tests else []):
        d = os.path.join(BASE, sub)
        for dp, _, fs in os.walk(d):
            for f in fs:
                p = os.path.join(dp, f)
                if dp == d and f.endswith(exts):
                    continue
                ext = os.path.splitext(f)[1].lower() or "(no ext)"
                n, b = out.get(ext, (0, 0))
                out[ext] = (n + 1, b + os.path.getsize(p))
    if not with_tests:
        d = os.path.join(BASE, "testcases")
        n = b = 0
        for dp, _, fs in os.walk(d):
            for f in fs:
                n += 1
                b += os.path.getsize(os.path.join(dp, f))
        out["testcases/ (not requested)"] = (n, b)
    return out


def local_modules():
    """Module names that resolve to a .py in this tree, for the import check."""
    mods = {}
    for sub in ("lib", "survey", "testcases"):
        d = os.path.join(BASE, sub)
        for f in os.listdir(d):
            if f.endswith(".py") and "-" not in f:      # `import a-b` is illegal
                mods[f[:-3]] = "%s/%s" % (sub, f)
    return mods


IMPORT_RE = re.compile(r'^\s*(?:import|from)\s+([A-Za-z_][A-Za-z0-9_]*)', re.M)


GROUP_RE = re.compile(r"(\S+)\s+(\d+)/(\d+)\s+binary-correct")


def check_suite(out):
    """Run the shipped suite and require a NON-DEGENERATE result.

    "Does it run" is not the check, and believing it was is what let a broken
    build print BUILD OK. Three states are reachable, and only the third is
    acceptable:

      no specs.json              -> traceback (loud, would have been caught)
      specs.json, no case data   -> EXIT 0, "0 correct"   <-- the dangerous one
      full data                  -> 22 correct, 101 cases across three groups

    The middle state is a clean exit over an empty corpus. Nothing raises,
    nothing warns, and the build looks finished. So this asserts the NUMBERS:
    every group must be present and fully scored, and the total must be the
    corpus size, not zero.
    """
    script = os.path.join(out, "testcases", "score-preflight.py")
    if not os.path.isfile(script):
        return ["testcases/score-preflight.py missing -- cannot verify the suite"]
    try:
        r = subprocess.run([sys.executable, script], cwd=os.path.join(out, "testcases"),
                           capture_output=True, text=True, timeout=300)
    except Exception as exc:                                  # noqa: BLE001
        return ["the shipped suite could not be run: %s" % exc]
    body = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        tail = [l for l in body.strip().splitlines() if l.strip()][-3:]
        return ["the shipped suite exits %d: %s" % (r.returncode, " / ".join(tail))]

    groups = GROUP_RE.findall(body)
    if not groups:
        return ["the shipped suite scored NO groups -- it ran, and measured "
                "nothing. The case metadata is missing or empty."]
    problems = []
    total = 0
    for name, got, want in groups:
        total += int(want)
        if int(want) == 0:
            problems.append("suite group %s has no cases" % name)
        elif got != want:
            problems.append("suite group %s scores %s/%s in the build (it is "
                            "%s/%s in the source tree)" % (name, got, want, want, want))
    if total == 0:
        problems.append("the shipped suite scored 0 cases in total")
    if not problems:
        print("  suite ................... %d cases across %d groups, all correct"
              % (total, len(groups)))
    return problems


def verify(out, with_tests):
    """Every check that would have caught a real past mistake."""
    problems, notes = [], []
    present = set()
    for dp, dirs, fs in os.walk(out):
        # A build directory can also be a working git repo -- that is how this
        # gets published. Never scan `.git/`: it is not shipped content, and
        # `.git/config` holds the remote URL, which contains the ACCOUNT NAME
        # and so trips the attribution rule on every check. Pruned rather than
        # exempted per-file, because the object store is compressed and would
        # give unreadable results either way.
        dirs[:] = [d for d in dirs if d != ".git"]
        for f in fs:
            present.add(os.path.relpath(os.path.join(dp, f), out)
                        .replace(os.sep, "/"))

    # 1. the home path, the account number, and attribution
    leaks, acct, attrib = [], [], []
    for rel in sorted(present):
        raw = read(os.path.join(out, rel.replace("/", os.sep)))
        if IDENT.search(raw):
            leaks.append(rel)
        if ACCOUNT.search(text(raw)):
            acct.append(rel)
        if rel not in ATTRIB_ALLOWED and ATTRIB.search(raw):
            attrib.append(rel)
    if leaks:
        problems.append("%d file(s) leak the operator's home path: %s"
                        % (len(leaks), ", ".join(leaks[:5])))
    if acct:
        problems.append("%d file(s) quote an account number: %s"
                        % (len(acct), ", ".join(acct[:5])))
    if attrib:
        problems.append("%d file(s) carry an attribution outside %s: %s"
                        % (len(attrib), " / ".join(sorted(ATTRIB_ALLOWED)),
                           ", ".join(attrib[:5])))

    # 1b. THE SCAN ABOVE IS BLIND TO PDFs, AND SAYS SO IN THE OUTPUT ANYWAY.
    #     Check 1 reads raw bytes. PDF page text lives in FlateDecode streams,
    #     so a PDF can pass a raw-byte scan for the operator name while
    #     rendering it at 24pt on page one -- and .pdf is in BINARY_EXT, so
    #     sanitise() never rewrites it either. That combination means the ONLY
    #     shipped file class the sanitiser cannot touch is also the one class
    #     the leak check cannot read. Decompress and scan the text layer and
    #     the document metadata (pdfTeX records /Author and /Creator, and a
    #     LaTeX build can pick up a username without anyone asking it to).
    pdfs = [r for r in sorted(present) if r.lower().endswith(".pdf")]
    if pdfs:
        try:
            import pypdf
        except ImportError:
            problems.append(
                "%d PDF(s) ship but pypdf is not installed, so their text "
                "layer CANNOT be scanned for the operator name. Install pypdf "
                "or remove the PDF -- an unscannable binary must not ship on "
                "the assumption it is clean." % len(pdfs))
        else:
            for rel in pdfs:
                p = os.path.join(out, rel.replace("/", os.sep))
                try:
                    doc = pypdf.PdfReader(p)
                    body = "\n".join(pg.extract_text() or "" for pg in doc.pages)
                    meta = " ".join(str(v) for v in (doc.metadata or {}).values())
                except Exception as exc:                      # noqa: BLE001
                    problems.append("%s could not be read for scanning: %s"
                                    % (rel, exc))
                    continue
                # IDENT is a BYTES pattern -- it is built to scan raw file
                # contents -- while extracted PDF text is str. Encode rather
                # than duplicating the pattern, so there is exactly one
                # definition of "names the operator" in the codebase.
                enc = (body + "\n" + meta).encode("utf-8", "replace")
                if IDENT.search(enc):
                    problems.append("%s leaks the operator's home path in its "
                                    "text layer or metadata (invisible to the "
                                    "byte scan)" % rel)
                if rel not in ATTRIB_ALLOWED and ATTRIB.search(enc):
                    problems.append("%s carries an attribution in its text "
                                    "layer or metadata -- pdfTeX records "
                                    "/Author and /Creator, and the reference "
                                    "documents must stand on their own" % rel)
                if ACCOUNT.search(body):
                    problems.append("%s quotes an account number in its text "
                                    "layer (invisible to the byte scan)" % rel)
                if not body.strip():
                    problems.append("%s has no extractable text -- it cannot "
                                    "be verified, and it is the document a "
                                    "customer is told to read first" % rel)

    # 2. nothing banned slipped through
    bad = [r for r in sorted(present)
           if r.lower().endswith(BANNED_EXT) or os.path.basename(r) in BANNED_NAME]
    if bad:
        problems.append("banned file(s) present: %s" % ", ".join(bad[:6]))

    # 3. the code parses
    for rel in sorted(present):
        if rel.endswith(".py"):
            try:
                compile(text(read(os.path.join(out, rel.replace("/", os.sep)))),
                        rel, "exec")
            except SyntaxError as e:
                problems.append("%s does not parse: %s" % (rel, e))

    # 4. THE ONE THAT CATCHES AN INCOMPLETE ALLOWLIST. A shipped module that
    #    imports a local module we did not ship fails at run time, on the
    #    customer's machine, having looked like a clean build here.
    mods = local_modules()
    shipped = {os.path.basename(r)[:-3] for r in present if r.endswith(".py")}
    missing = {}
    for rel in sorted(present):
        if not rel.endswith(".py"):
            continue
        body = text(read(os.path.join(out, rel.replace("/", os.sep))))
        for name in set(IMPORT_RE.findall(body)):
            if name in mods and name not in shipped:
                missing.setdefault(mods[name], []).append(rel)
    for mod, users in sorted(missing.items()):
        problems.append("%s is imported by %s but is NOT in the build"
                        % (mod, ", ".join(sorted(users)[:3])))

    # 4b. EVERY THIRD-PARTY IMPORT IS DECLARED. The check above catches a
    #     missing module of OURS; this catches a missing dependency of
    #     someone else's. Both fail the same way on the customer's machine --
    #     ImportError, on first use, from a build that verified clean. Added
    #     2026-08-09 after the .lpf readers moved to PySpeos and nothing in
    #     the distribution recorded the new dependency.
    req_path = os.path.join(out, "requirements.txt")
    declared = set()
    if os.path.isfile(req_path):
        for line in text(read(req_path)).splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                # `ansys-speos-core` is imported as `ansys.speos.core`
                declared.add(re.split(r"[<>=!\[]", line)[0].strip().lower()
                             .replace("-", "").replace("_", ""))
    third = {}
    for rel in sorted(present):
        if not rel.endswith(".py"):
            continue
        body = text(read(os.path.join(out, rel.replace("/", os.sep))))
        for name in set(IMPORT_RE.findall(body)):
            if name in STDLIB or name in shipped or name in mods \
                    or name in ANSYS_PROVIDED or name in BUILD_ONLY:
                continue
            third.setdefault(name, []).append(rel)
    for name, users in sorted(third.items()):
        flat = name.lower().replace("-", "").replace("_", "")
        if not any(flat == d or d.startswith(flat) or flat.startswith(d)
                   for d in declared):
            problems.append(
                "third-party module `%s` is imported by %s but is not declared "
                "in requirements.txt" % (name, ", ".join(sorted(users)[:3])))

    # 4c. ROOT-LEVEL FILES INVOKED BY PATH. The import graph sees `import x`;
    #     it is blind to `os.path.join(BASE, "export-odx.ps1")` and to a
    #     PowerShell script run as a subprocess. That blindness shipped a
    #     distribution that passed every check and died at the third pipeline
    #     stage. Only names that EXIST at the source root are required, so
    #     globs and format strings cannot produce false positives.
    for rel in sorted(present):
        if not rel.endswith((".py", ".ps1")):
            continue
        body = text(read(os.path.join(out, rel.replace("/", os.sep))))
        for m in ROOT_REF.finditer(body):
            if m.group(1):
                name = "/".join(x.strip().strip('"')
                                for x in m.group(1).split(","))
            else:
                name = m.group(2).replace("\\", "/")
            # EXECUTABLES ONLY. The first version required every referenced
            # file that exists at source, and produced 11 false positives:
            # generated artefacts (`survey/survey-results.json`,
            # `fleet-final.log`) and the six corpus `.zmx`, which are Zemax's
            # samples and are deliberately never shipped. A script invoked by
            # path must travel with the code; a data file it reads or writes
            # must not.
            if not name.endswith((".py", ".ps1", ".sh")):
                continue
            if not os.path.isfile(os.path.join(BASE, name.replace("/", os.sep))):
                continue                # a glob, a directory, or a path fragment
            if name not in present:
                problems.append(
                    "%s invokes `%s` by path, which is not in the build"
                    % (rel, name))

    # 5. NOTHING THE BUILDER WOULD SHIP IS ABSENT. Every other check inspects
    #    what IS there; none of them notice what is not. Removing specs.json
    #    from a finished build passed every check above, because the scorer
    #    that runs reads its truth from the per-case files and never touches
    #    it -- so one deleted file left a build that scored perfectly and
    #    would have crashed the OTHER entry point on the customer's first run.
    #    Comparing against the manifest catches any omission, including the
    #    ones no runtime check happens to exercise.
    expected = {rel for rel, _ in sources(with_tests)}
    absent = sorted(expected - present)
    if absent:
        problems.append("%d file(s) the build should contain are missing: %s%s"
                        % (len(absent), ", ".join(absent[:5]),
                           "" if len(absent) <= 5 else ", ..."))

    # 6. the config story is intact
    if "straylight.toml.example" not in present:
        problems.append("no straylight.toml.example -- nothing to configure from")
    if "lib/settings.py" not in present:
        problems.append("no lib/settings.py -- nothing reads the config")

    # 7. a customer must not need a file we did not ship at the root
    for name in ROOT_FILES:
        if name not in present:
            problems.append("missing root file %s" % name)

    # 8. THE BUILD MUST TELL ITS READER WHERE TO START. Check 7 proves the two
    #    documents are present; presence is not the property that matters. A
    #    stub README satisfies every other rule in this file -- it parses (it
    #    is not code), it leaks nothing, it is not banned, it is in the
    #    manifest -- and leaves the customer exactly where they were before it
    #    existed. So require that the README actually names the config file
    #    they must create and the command they must run, and that it points at
    #    the guide. Same principle as check_suite: "it exists" and "it works"
    #    are different questions, and this codebase has been burned by
    #    answering the first while believing it answered the second.
    if DOC_README in present:
        body = text(read(os.path.join(out, DOC_README)))
        missing_refs = [m for m in DOC_MUST_MENTION if m not in body]
        if missing_refs:
            problems.append("%s does not mention %s -- a reader cannot get "
                            "from the unpacked folder to a first run"
                            % (DOC_README, ", ".join(missing_refs)))
        if DOC_GUIDE not in body:
            problems.append("%s does not point at %s, so the install guide "
                            "ships but nothing directs anyone to it"
                            % (DOC_README, DOC_GUIDE))
        if len(body.strip()) < 800:
            problems.append("%s is %d chars -- too short to be the entry point"
                            % (DOC_README, len(body.strip())))

    if not with_tests:
        notes.append("testcases/ excluded (pass --with-testcases to include it)")
    else:
        # Precise about WHICH half scores. The earlier wording -- "the suite
        # scores" -- was too generous: measured 2026-08-09, score-loop.py from
        # a distribution reports 0 of 101 cases with a stray delta, because the
        # reductions live in SPEOS output files/ (450 MB of .lpf, 32 MB of
        # .xmp) that the allowlist excludes. It exits 0 and prints
        # "complete-noresults 66", which is the SAME signature as the historic
        # outdir() bug that silently lost every reduction -- so saying it
        # plainly here is the difference between an expected limitation and a
        # customer reporting a catastrophe.
        notes.append("gate scoring WORKS from this build (score-preflight: "
                     "101 cases, 3 groups). Loop scoring does NOT and cannot: "
                     "score-loop.py needs SPEOS output files/, which is 480 MB "
                     "of run artefacts and is excluded -- expect "
                     "`complete-noresults` for every case.")
        notes.append("the suite's .zmx prescriptions are NOT included either "
                     "-- they are Zemax's samples -- so the cases cannot be "
                     "rebuilt. The corpus export is the artefact that carries "
                     "evidence; this build carries the code.")
        problems.extend(check_suite(out))
    return problems, notes


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(BASE),
                                                  "straylight-pipeline"))
    ap.add_argument("--with-testcases", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="verify an existing build; write nothing")
    a = ap.parse_args()
    out = os.path.abspath(a.out)

    if not a.check:
        files = list(sources(a.with_testcases))
        for rel, src in files:
            dst = os.path.join(out, rel.replace("/", os.sep))
            d = os.path.dirname(dst)
            if not os.path.isdir(d):
                os.makedirs(d)
            raw = read(src)
            # Sanitise every TEXT file, identified by what must NOT be touched
            # rather than by a list of what should. The case metadata is .json
            # and all 303 files of it carry `C:/Users/<user>/...`; an allowlist of
            # source extensions silently skipped them, so the first build to
            # include the suite would have shipped the operator's name in data
            # while reporting "operator name .... absent" for the code.
            # Binary payloads (the BSDF) are copied byte for byte -- sanitise()
            # is a text rewrite and would corrupt them.
            if os.path.splitext(rel)[1].lower() in BINARY_EXT:
                shutil.copyfile(src, dst)
            else:
                write(dst, sanitise(raw))
        print("=== build-distribution -> %s ===" % out)
        print("  shipped              %d files, %.0f KB"
              % (len(files),
                 sum(os.path.getsize(s) for _, s in files) / 1024.0))
        by = {}
        for rel, _ in files:
            k = rel.split("/")[0] if "/" in rel else "(root)"
            by[k] = by.get(k, 0) + 1
        for k in sorted(by):
            print("      %-14s %d" % (k, by[k]))

        print("  EXCLUDED (counted, never silent):")
        ex = excluded(a.with_testcases)
        for ext in sorted(ex, key=lambda e: -ex[e][1]):
            n, b = ex[ext]
            print("      %-28s %5d files  %8.1f MB" % (ext, n, b / 1048576.0))
        print("      %-28s %5d files  %8.1f MB"
              % ("TOTAL LEFT BEHIND", sum(n for n, _ in ex.values()),
                 sum(b for _, b in ex.values()) / 1048576.0))
    else:
        print("=== build-distribution --check %s ===" % out)
        if not os.path.isdir(out):
            print("  no build at that path")
            return 1

    problems, notes = verify(out, a.with_testcases)
    print("\n=== verification ===")
    for n in notes:
        print("  note: %s" % n)
    if problems:
        for p in problems:
            print("  FAIL: %s" % p)
        print("\n  %d problem(s) -- this build must not ship" % len(problems))
        return 1
    print("  operator home path ..... absent")
    print("  account number ......... absent")
    print("  attribution ............ confined to %s"
          % " / ".join(sorted(ATTRIB_ALLOWED)))
    print("  banned file types ...... absent")
    print("  python files ........... all parse")
    print("  local imports .......... all satisfied within the build")
    print("  config ................. example present, machine config withheld")
    print("  entry point ............ README.md points at the install guide")
    print("  shipped PDFs ........... text layer and metadata scanned, clean")
    print("\n  BUILD OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
